name: IPA
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 */3 * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
         python-version: "3.10"

      - name: 安装依赖项
        run: |
          python -m pip install --upgrade pip
          pip install requests bs4 pytz

      - name: 运行脚本
        run: python py/ipa.py

      - name: 提交文件
        run: |
          git config --local user.email "${{ secrets.USER_EMAIL }}"
          git config --local user.name "${{ secrets.USER_NAME }}"
          #echo "https://github.com/${{ github.repository }}:${{ secrets.REPO_TOKEN }}" > .git-credentials
          git add .
          git commit -m "ipa应用商店更新合并" -a || true
          git commit -m "Add new JSON files" || echo "No changes to commit"
          git push
          git remote
          
      - name: Bark通知
        run: |
          curl "https://api.day.app/${{ secrets.BARK_KEY }}/ipa应用商店更新合并完成!?icon=https://cdn.jsdelivr.net/gh/xiaoji235/IPA-Store/github.png"
